/**:
  ros__parameters:
    common:
      lid_topic: "/airy_points"
      imu_topic: "/airy_imu"  # /mavros/imu/data /ouster/imu /imu/data
      time_sync_en: false      # ONLY turn on when external time synchronization is really not possible
      time_offset_lidar_to_imu: 0.1   #测试为0.1s，当自动对齐打开时设为0.0；当自动对齐关闭时，设为0.1
                                      # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                      # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

    preprocess:
      lidar_type: 5  # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 5 for RoboSense Airy
      scan_line: 96  #激光扫描线数
      timestamp_unit: 0  # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 0.2    #近距离盲区（米）

    mapping:
      max_search_dist_surf: 1.0  # default: 5
      num_sub_cloud: 1 # This is int, should be fine
      acc_cov: 0.5     #IMU 加速度的噪声协方差0.1
      gyr_cov: 0.5     #IMU 角速度的噪声协方差0.1
      b_acc_cov: 0.0001  #IMU 零偏漂移协方差
      b_gyr_cov: 0.0001
      fov_degree: 120.0  #雷达水平视场角
      det_range: 60.0  #最大探测距离（米）
      extrinsic_est_en: false  # true: enable the online estimation of IMU-LiDAR extrinsic
      gravity_align: false     #开启重力对齐
      extrinsic_T: [0.004250, 0.004180, -0.004460]
      extrinsic_R: [0.001474, -0.999996, -0.002458,
                    -0.999998, -0.001470, -0.001425,
                    0.001422, 0.002460, -0.999996]
      # extrinsic_T: [0.0, 0.0, 0.0]
      # extrinsic_R: [0.0, 1.0, 0.0,
      #               -1.0, 0.0, 0.0,
      #               0.0, 0.0, -1.0]
      

    publish:
      path_en: true  #是否在 Rviz 里显示机器人的运动轨迹
      scan_publish_en: true  # 是否发布处理后的实时点云（用于看效果）
      dense_publish_en: true  # 是否发布高密度地图
      scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
      tf_en: true
      
    pcd_save:
      pcd_save_en: false  #关机时是否自动把地图保存成 .pcd 文件
      interval: -1  # how many LiDAR frames saved in each pcd file;
                    # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
